# Exported from Render on 2025-03-12T21:00:38Z
services:
- type: web
  name: Kim
  runtime: python
  repo: https://github.com/Naruto091427/Kim
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn your_application.wsgi
version: "1"
